NAME = megaphone

CPP = clang++

FLAGS = -Wall -Wextra -Werror

RM = rm -f

MAIN = MegaPhone.cpp

$(NAME): $(MAIN)
	$(CPP) $(MAIN) $(FLAGS) -o $(NAME)

all : $(NAME)

clean: $(RM) $(NAME)

re:	clean all
