NAME = PhoneBook

CPP = clang++

FLAGS = -Wall -Wextra -Werror

RM = rm -f

MAIN = Main.cpp

SRCS =

$(NAME): $(MAIN)
	$(CPP) $(MAIN) $(FLAGS) -o $(NAME)

all : $(NAME)

clean: $(RM) $(NAME)

re:	clean all
